"""Add cake inrernal notes

Revision ID: 2097973f47b8
Revises: e0f55fbf534f
Create Date: 2026-09-07 20:59:09.105388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2097973f47b8'
down_revision: Union[str, Sequence[str], None] = 'e0f55fbf534f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cakes', sa.Column('internal_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cakes', 'internal_notes')
    # ### end Alembic commands ###
