"""Add orders and order items

Revision ID: d89605bb67bf
Revises: 2097973f47b8
Create Date: 2026-09-08 18:06:00.666794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89605bb67bf'
down_revision: Union[str, Sequence[str], None] = '2097973f47b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('customer_note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'confirmed', 'in_preparation', 'ready', 'completed', 'cancelled')", name='ck_orders_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('cake_id', sa.Integer(), nullable=False),
    sa.Column('cake_name', sa.String(), nullable=False),
    sa.Column('unit_price_kopiyky', sa.Integer(), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity'),
    sa.CheckConstraint('unit_price_kopiyky > 0', name='ck_order_items_price'),
    sa.CheckConstraint('weight_grams > 0', name='ck_order_items_weight'),
    sa.ForeignKeyConstraint(['cake_id'], ['cakes.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_cake_id'), 'order_items', ['cake_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_cake_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
