"""Add cake availability

Revision ID: e0f55fbf534f
Revises: 6eb3ad4c319c
Create Date: 2026-09-07 17:52:55.610112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f55fbf534f'
down_revision: Union[str, Sequence[str], None] = '6eb3ad4c319c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cakes', sa.Column('is_available', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cakes', 'is_available')
    # ### end Alembic commands ###
